name = Base Layout
description = Base layout for robotheme
preview = preview.png
template = base-layout
base theme = omega


; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content_top] = Content Top
regions[content_bottom_first] = Content Bottom First
regions[content_bottom_second] = Content Bottom Second
regions[content_bottom_third] = Content Bottom Third
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[postscript_first] = Postscript First
regions[postscript_second] = Postscript Second
regions[footer_first]   = First Footer
regions[footer_second]  = Second Footer
regions[footer_third]   = Third Footer

; Stylesheets
stylesheets[all][] = css/layouts/base/base.layout.css
stylesheets[all][] = css/layouts/base/base.layout.no-query.css

