<?php

/**
 * @file
 * owlcarousel_fields.module
 */

/**
 * Implements hook_field_formatter_info().
 */
function owlcarousel_fields_field_formatter_info() {
  return array(
    'owlcarousel_formatter' => array(
      'label' => t('Owl Carousel'),
      'field types' => array('image', 'text', 'text_long', 'text_with_summary', 'paragraphs', 'entityreference'),
      'settings'  => array(
        'settings_group' => 'default',
        'image_style' => 'large',
        'trim_length' => '',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function owlcarousel_fields_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();
  $element['settings_group'] = array(
    '#type' => 'select',
    '#title' => t('Settings Group'),
    '#description' => t('Select the settings group to apply.'),
    '#default_value' => $settings['settings_group'],
    '#options' => owlcarousel_instance_callback_list(),
  );

  if ($field['type'] == 'image') {
    $element['image_style'] = array(
      '#type' => 'select',
      '#title' => t('Image Style'),
      '#description' => t('Apply image style.'),
      '#default_value' => $settings['image_style'],
      '#options' => image_style_options(),
    );
  }

  if (strpos($field['type'], 'text_') !== false) {
    $element['trim_length'] = array(
      '#title' => t('Trim length'),
      '#type' => 'textfield',
      '#size' => 10,
      '#default_value' => $settings['trim_length'],
      '#element_validate' => array('element_validate_integer_positive'),
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function owlcarousel_fields_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $message = '@settings applied to carousel instance.';
  if ($field['type'] == 'image') {
    $message = '@settings with image style @style applied to carousel instance.';
  }

  $summary = t($message, array(
    '@settings' => $settings['settings_group'],
    '@style' => $settings['image_style'],
  ));

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function owlcarousel_fields_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  // Format carousel settings.
  $items_group = FALSE;
  $settings_group = array(
    'instance' => $settings['settings_group'],
    'attributes' => array(
      'id' => array(
        'default' => drupal_html_id('owlcarousel_fields_' . $instance['id'])
      ),
    ),
  );

  // Format carousel items.
  switch ($field['type']) {
    case 'text':
    case 'text_long':
    case 'text_with_summary':
      foreach ($items as $item) {
        if (!empty($item['summary'])) {
          $output = _text_sanitize($instance, $langcode, $item, 'summary');
        }
        else {
          $output = _text_sanitize($instance, $langcode, $item, 'value');
          if (isset($display['settings']['trim_length'])) {
            $output = text_summary($output, $instance['settings']['text_processing'] ? $item['format'] : NULL, $display['settings']['trim_length']);
          }
        }
 
        $items_group[]['row'] = $output;
      }
    break;
    case 'image':
      foreach ($items as $item) {
        $vars = array(
          'path' => $item['uri'],
          'width' => $item['width'],
          'height' => $item['height'],
          'alt' => $item['alt'],
          'title' => $item['title'],
        );

        if (empty($settings['image_style'])) {
          $items_group[]['row'] = theme('image', $vars);
        }
        else {
          $vars += array('style_name' => $settings['image_style']);
          $items_group[]['row'] = theme('image_style', $vars);
        }
      }
    break;
  }

  // Only render if we have items.
  if ($items_group) {
    $element = array(
      '#theme' => 'owlcarousel',
      '#items' => $items_group,
      '#settings' => $settings_group,
    );
  }

  return $element;
}
